/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Validator, ValidatorEntry, } from "./validators";
export namespace Components {
    interface AeValidateComponent {
        "validate": () => Promise<void>;
        "validator": Array<string | ValidatorEntry | Validator<string>>;
        "value": string;
    }
}
declare global {
    interface HTMLAeValidateComponentElement extends Components.AeValidateComponent, HTMLStencilElement {
    }
    var HTMLAeValidateComponentElement: {
        prototype: HTMLAeValidateComponentElement;
        new (): HTMLAeValidateComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ae-validate-component": HTMLAeValidateComponentElement;
    }
}
declare namespace LocalJSX {
    interface AeValidateComponent {
        "onChanged"?: (event: CustomEvent<string>) => void;
        "validator"?: Array<string | ValidatorEntry | Validator<string>>;
        "value"?: string;
    }
    interface IntrinsicElements {
        "ae-validate-component": AeValidateComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ae-validate-component": LocalJSX.AeValidateComponent & JSXBase.HTMLAttributes<HTMLAeValidateComponentElement>;
        }
    }
}
